[providers]
providers = ["php", "node"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm ci"
]

[phases.build]
cmds = [
    "npm run build",
    "chmod +x docker/start.sh"
]

[start]
cmd = "sh docker/start.sh"
