[build]
builder = "nixpacks"
buildCommand = "composer install --no-dev --optimize-autoloader"

[deploy]
startCommand = "sh docker/start.sh"
healthcheckPath = "/up"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
